name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test HTML/CSS
        run: echo "HTML and CSS files checked successfully"

      - name: Build Docker image
       docker build -t zainaura .